server:
  port: 8081

spring:
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.80.37:3306/oasis?useSSL=false&&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

management:
  endpoints:
    jmx:
      exposure:
        include: "*" # 或者设置为promethues，只开放promethues
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      datadog:
        application-key: ${spring.application.name}
    enable:
      jvm: true

info:
  app:
    name: certificate-manager
